# Generated by Django 2.2 on 2021-05-31 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('information', models.TextField(max_length=500, verbose_name='Información')),
                ('acquisition_date', models.DateTimeField(verbose_name='Fecha de adquisición')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagen')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['acquisition_date'],
            },
        ),
    ]
