# Generated by Django 2.2 on 2021-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(upload_to='media/products', verbose_name='Imagen'),
        ),
    ]
